// Mocks generated by Mockito 5.1.0 from annotations
// in tab_news/test/presentation/presenters/getx_feed_presenter_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tab_news/domain/entities/entities.dart' as _i4;
import 'package:tab_news/domain/usecases/load_contents.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [LoadContents].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadContents extends _i1.Mock implements _i2.LoadContents {
  MockLoadContents() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ContentEntity>> loadContents() =>
      (super.noSuchMethod(Invocation.method(#loadContents, []),
              returnValue:
                  Future<List<_i4.ContentEntity>>.value(<_i4.ContentEntity>[]))
          as _i3.Future<List<_i4.ContentEntity>>);
}
